In [2]:
import numpy as np

# Одновимірний масив з першими 10-ма натуральними числами
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
print(vector)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [4]:
# Lвовимірний масив (матрицю) розміром 3x3, заповнений нулями.
zero_matrix = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]], dtype=int)

print(zero_matrix)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
random_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))

print(random_matrix_5x5)

[[ 2  9  1  3  6]
 [ 5 10  5  8  4]
 [ 2  1  8  9  6]
 [ 5  8  1  4  9]
 [ 6  5  5  5  2]]
