ЗАВДАННЯ 1

In [2]:
import numpy as np

# Одновимірний масив з першими 10-ма натуральними числами
vector_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
vector_2 = np.arange(11, dtype=float)
print(vector_1)
print(vector_2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# Lвовимірний масив (матрицю) розміром 3x3, заповнений нулями.
zero_matrix_1 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]], dtype=int)
zero_matrix_2 = np.zeros((3, 3), dtype=int)
print(zero_matrix_1)
print(zero_matrix_2)

In [ ]:
# Масив розміром 5x5, з випадковими цілими числами в діапазоні від 1 до 10
random_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))

print(random_matrix_5x5)

In [ ]:
# Масив розміром 4x4, з випадковими дійсними числами в діапазоні від 0 до 1
random_matrix_4x4 = np.random.randint(0, 2, size=(4, 4))

print(random_matrix_4x4)

In [ ]:
# Два одновимірні масиви розміром 5, заповнені випадковими цілими числами
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)

# Поелементні операції
sum_array = a + b
diff_array = a - b
multipli_array = a * b

print(a)
print(b)
print(f"Sum: {sum_array}")
print(f"Difference: {diff_array}")
print(f"Multipli: {multipli_array}")

In [ ]:
# Два вектори розміром 7, заповнені довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# Скалярний добуток
dot_product = np.dot(vector1, vector2)

print(f"Vector 1: {vector1}")
print(f"Vector 2: {vector2}")
print(f"Dot product: {dot_product}")

In [ ]:
# Дві матриці розміром 2x2 та 2x3, заповнені випадковими цілими числами
matrix_2x2 = np.random.randint(1, 11, (2, 2))
matrix_2x3 = np.random.randint(1, 11, (2, 3))

# Множення матриць
dot_matrix = np.dot(matrix_2x2, matrix_2x3)

print(f"2x2 Matrix:\n {matrix_2x2}")
print(f"2x3 Matrix:\n {matrix_2x3}")
print(f"Dot Matrix:\n {dot_matrix}")

In [ ]:
# Матриця розміром 3x3, заповнена випадковими цілими числами
matrix_3x3 = np.random.randint(1, 11, (3, 3))

# Обернена матриця
inverse_matrix = np.linalg.inv(matrix_3x3)

print(f"3x3 Matrix:\n {matrix_3x3}")
print(f"Inverse Matrix:\n {inverse_matrix}")


In [ ]:
# Матриця розміром 4x4, заповнена випадковими дійсними числами
matrix_4x4 = np.random.rand(4, 4)

# Транспонована матриця
transposed_matrix = matrix_4x4.T

print(f"4x4 Matrix:\n {matrix_4x4}")
print(f"Transposed Matrix:\n {transposed_matrix}")

In [ ]:
# Матриця розміром 3x4 та вектор розміром 4, заповнені випадковими цілими числами
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)

# Множення матриці на вектор
dot_vector = np.dot(matrix_3x4, vector_4)

print(f"3x4 Matrix:\n {matrix_3x4}")
print(f"4-element Vector: {vector_4}")
print(f"Dot Vector: {dot_vector}")


In [ ]:
# Матриця розміром 2x3 та вектор розміром 3, заповнені випадковими дійсними числами
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)

# Множення матриці на вектор
dot_vector = np.dot(matrix_2x3, vector_3)

print(f"2x3 Matrix:\n {matrix_2x3}")
print(f"3-element Vector: {vector_3}")
print(f"Dot Vector: {dot_vector}")


In [ ]:
# Дві матриці розміром 2x2, заповнені випадковими цілими числами
matrix1_2x2 = np.random.randint(1, 11, (2, 2))
matrix2_2x2 = np.random.randint(1, 11, (2, 2))

# Поелементне множення
elementwise = matrix1_2x2 * matrix2_2x2

print(f"Matrix 1:\n {matrix1_2x2}")
print(f"Matrix 2:\n {matrix2_2x2}")
print(f"Elementwise:\n {elementwise}")


In [ ]:
# Дві матриці розміром 2x2, заповнені випадковими цілими числами
matrix1_2x2 = np.random.randint(1, 11, (2, 2))
matrix2_2x2 = np.random.randint(1, 11, (2, 2))

# Добуток матриць
dot_matrix = np.dot(matrix1_2x2, matrix2_2x2)

print(f"Matrix 1:\n {matrix1_2x2}")
print(f"Matrix 2:\n {matrix2_2x2}")
print(f"Dot Matrix:\n {dot_matrix}")


In [ ]:
# Матриця розміром 5x5, заповнена випадковими цілими числами від 1 до 100
matrix_5x5 = np.random.randint(1, 101, (5, 5))

# Сума елементів матриці
matrix_sum = np.sum(matrix_5x5)

print(f"5x5 Matrix:\n {matrix_5x5}")
print(f"Sum of elements: {matrix_sum}")


In [ ]:
# Дві матриці розміром 4x4, заповнені випадковими цілими числами
matrix1_4x4 = np.random.randint(1, 11, (4, 4))
matrix2_4x4 = np.random.randint(1, 11, (4, 4))

# Різниця матриць
matrix_difference = matrix1_4x4 - matrix2_4x4

print(f"Matrix 1:\n {matrix1_4x4}")
print(f"Matrix 2:\n {matrix2_4x4}")
print(f"Matrix Difference:\n {matrix_difference}")

In [ ]:
# Матриця розміром 3x3, заповнена випадковими дійсними числами
matrix_3x3 = np.random.rand(3, 3)

# Вектор-стовпчик з сумою елементів кожного рядка
row_sums = np.sum(matrix_3x3, axis=1).reshape(-1, 1)

print(f"3x3 Matrix:\n {matrix_3x3}")
print(f"Row sums:\n {row_sums}")


In [ ]:
# Матриця розміром 3x4 з довільними цілими числами
matrix_3x4 = np.random.randint(1, 11, (3, 4))

# Матриця з квадратами цих чисел
squared_matrix = np.square(matrix_3x4)

print(f"3x4 Matrix:\n {matrix_3x4}")
print(f"Squared Matrix:\n {squared_matrix}")


In [ ]:
# Вектор розміром 4, заповнений випадковими цілими числами від 1 до 50
vector_4 = np.random.randint(1, 51, 4)

# Вектор з квадратними коренями цих чисел
sqrt_vector = np.sqrt(vector_4)

print(f"Original Vector: {vector_4}")
print(f"Square Root Vector: {sqrt_vector}")


ЗАВДАННЯ 2

In [3]:
# Замінюємо усі непарні числа в arr на -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
# Створюємо та перетворюємо 1D-масив на 2D-масив із 2 рядками
arr = np.arange(1, 11)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Створіть два двовимірні масиви a і b, та складіть масиви їх вертикально
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))
c = np.vstack((a, b))
print(c)

In [10]:
# Input:a = np.array([1,2,3])
# Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1, 2, 3])
b = np.repeat(a, 3)
c = np.tile(a, 3)
output = np.concatenate((b, c))
print(output)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
# Спільні елементи між a і b
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_elements = np.intersect1d(a, b)
print(common_elements)

[2 4]


In [13]:
# Позиції перших 5 максимальних значень у заданому масиві
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
indices = np.argsort(a)[-5:][::-1]
print(indices)

[15 10  3  7 18]


In [14]:
# Вилучіть усі значення NaN із одновимірного масиву
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_non_nan = a[~np.isnan(a)]
print(a_non_nan)

[1. 2. 3. 5. 6. 7.]


In [ ]:
# Евклідова відстань між двома масивами a і b
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
euclidean_distance = np.linalg.norm(a - b)
print(euclidean_distance)

In [15]:
# індекс 5-го повторення числа 1 у масиві x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
index_5th = np.where(x == 1)[0][4]
print(index_5th)

8
